# Generated by Django 2.1.4 on 2019-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190124_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='shortcut',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
