# Generated by Django 2.1.4 on 2019-02-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_shortcut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='shortcut',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
