# Generated by Django 2.1.4 on 2019-02-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190204_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
